<?php
App::uses('AppController', 'Controller');
/**
 * Abonos Controller
 * Generated by Petit Four the online baking tool for CakePHP: http://patisserie.keensoftware.com
 * @property Abono $Abono
 */
class AbonosController extends AppController {

public $uses = array("Paciente", "Patologia", "Tratamiento", "Abono");

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->Abono->recursive = 0;
		$this->set('abonos', $this->paginate());
	}

}
