<?php
App::uses('AppController', 'Controller');
/**
 * Patologias Controller
 * Generated by Petit Four the online baking tool for CakePHP: http://patisserie.keensoftware.com
 * @property Patologia $Patologia
 */
class PatologiasController extends AppController {

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->Patologia->recursive = 0;
		$this->set('patologias', $this->paginate());
	}

/**
 * view method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function view($id = null) {
		if (!$this->Patologia->exists($id)) {
			throw new NotFoundException(__('Invalid Patologia'));
		}
		$options = array('conditions' => array('Patologia.' . $this->Patologia->primaryKey => $id));
		$this->set('patologia', $this->Patologia->find('first', $options));
	}

/**
 * add method
 *
 * @return void
 */
	public function add() {
		if ($this->request->is('post')) {
			$this->Patologia->create();
			if ($this->Patologia->save($this->request->data)) {
				$this->Session->setFlash(__('The Patologia has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The Patologia could not be saved. Please, try again.'));
			}
		}
	}

/**
 * edit method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function edit($id = null) {
		if (!$this->Patologia->exists($id)) {
			throw new NotFoundException(__('Invalid Patologia'));
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			if ($this->Patologia->save($this->request->data)) {
				$this->Session->setFlash(__('The Patologia has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The Patologia could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('Patologia.' . $this->Patologia->primaryKey => $id));
			$this->request->data = $this->Patologia->find('first', $options);
		}
	}

/**
 * delete method
 *
 * @throws NotFoundException
 * @throws MethodNotAllowedException
 * @param int id
 * @return void
 */
	public function delete($id = null) {
		$this->Patologia->id = $id;
		if (!$this->Patologia->exists()) {
			throw new NotFoundException(__('Invalid Patologia'));
		}
		$this->request->onlyAllow('post', 'delete');
		if ($this->Patologia->delete()) {
			$this->Session->setFlash(__('The Patologia has been deleted.'));
		} else {
			$this->Session->setFlash(__('The Patologia could not be deleted. Please, try again.'));
		}
		return $this->redirect(array('action' => 'index'));
	}
}
